title: Guillermo Federico Carrilao Avila
description: Security Analyst, Researcher, Data Analyst
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github:
  linkedin_url: https://www.linkedin.com/in/guillermo-federico-carrilao-avila-6998a8150/
  github_url: https://github.com/gcarrilao
