# Site settings
title: CV - Guillermo Federico Carrilao Avila
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Guillermo Federico Carrilao Avila
user_description: I am currently working as an analyst in security, since 2018. I also have work experience in Web development, Unix administrator, network administrator, database administrator. In the academic area, since 2017 I have been working as a research fellow of the Faculty of computing - National University of La Plata to perform data mining, and I have published a few research papers. To finish my degree course I am developing my final thesis focusing on Machine learning and Natural Language Processing. I have work experiences in the Government of the Province of Buenos Aires, Argentina, in the Superior Center for the Processing of Information (CeSPI), and as a teacher of the university in "Algorithms and Data Structures" and "Concurrent Programming" of the Bachelor's degree in Systems. My specialties include; Pentesting web, security tools management (Acunetix, Nessus, Arachni), Firewall, Data mining, Big Data, web development (Python, PHP, Ruby frameworks), database management (SQL, noSQL).
user_title: Security Analyst
email: federico.carrilao.avila@gmail.com
twitter_username: lorem_ip
github_username: gcarrilao
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
